# Generated by Django 4.2.7 on 2023-12-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_income_incomecategory_incomedetails_income_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='category',
            new_name='income_category',
        ),
    ]
