# Generated by Django 4.2.7 on 2023-12-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_rename_category_income_income_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
    ]
