# Generated by Django 4.2.7 on 2023-12-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_remove_contract_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetails',
            name='customer_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
