# Generated by Django 4.2.7 on 2023-12-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contractdetails_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrasferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=200)),
                ('payment_day', models.IntegerField(blank=True, null=True)),
                ('payment_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.transferordercategory')),
            ],
        ),
        migrations.CreateModel(
            name='TrasferOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('transfer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.trasferorder')),
            ],
        ),
    ]
