# Generated by Django 4.2.7 on 2023-12-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_transferordercategory_trasferorder_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrasferOrder',
            new_name='TransferOrder',
        ),
        migrations.RenameModel(
            old_name='TrasferOrderDetails',
            new_name='TransferOrderDetails',
        ),
    ]
