# Generated by Django 4.2.7 on 2023-12-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_rename_trasferorder_transferorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=200)),
                ('payment_day', models.IntegerField(blank=True, null=True)),
                ('payment_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PocketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PocketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('pocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.pocket')),
            ],
        ),
        migrations.AddField(
            model_name='pocket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.pocketcategory'),
        ),
    ]
